version: "3.9"
services:
  app_blue:
    build: ./app_blue
    container_name: app_blue

  app_green:
    build: ./app_green
    container_name: app_green

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app_blue
      - app_green
