version: "3.9"

services:
  app_blue:
    build: ./app_blue
    ports:
      - "8081:8081"
    environment:
      - PORT=8081

  app_green:
    build: ./app_green
    ports:
      - "8082:8082"
    environment:
      - PORT=8082

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app_blue
      - app_green
